import { ScriptItem } from './types';

export const SCRIPTS: ScriptItem[] = [
  {
    id: '99-nights',
    title: '99 Nights Script',
    description: 'Complete automation, ESP system, god mode and infinite stamina',
    imageUrl: 'https://i.postimg.cc/htmsHLZS/maxresdefault-7.jpg',
    iconUrl: 'https://i.postimg.cc/15G93p7N/1763419372969.jpg',
    tags: ['Auto Farm', 'ESP', 'God Mode', 'Infinite Stamina'],
    badges: [{ text: 'BEST', type: 'top' }],
    stats: { rating: '5.0', users: '2.5M', size: '2.1MB' },
    link: 'https://gamlob.online/cl/i/ex625q',
  },
  {
    id: 'steal-brainrot',
    title: 'Steal a Brainrot Script',
    description: 'Instant steal, ESP vision, fly mode and unlimited speed boost',
    imageUrl: 'https://i.postimg.cc/59Q7MWrb/hq720-9.jpg',
    iconUrl: 'https://i.postimg.cc/3x9Yg3TT/steal-a-brainrot-button-1756389161332.jpg',
    tags: ['Instant Steal', 'ESP', 'Fly Mode', 'Speed'],
    badges: [{ text: 'NEW', type: 'new' }],
    stats: { rating: '4.9', users: '2.9M', size: '1.8MB' },
    link: 'https://gamlob.online/cl/i/xp62dv',
  },
  {
    id: 'fish-it',
    title: 'Fish It Script',
    description: 'Auto cast and reel, perfect catch timing, fish radar and instant hotspot teleport',
    imageUrl: 'https://i.postimg.cc/Vvjc58gr/hq720.jpg',
    iconUrl: 'https://i.postimg.cc/1XxQ9tpW/roblox-fish-it-header.png',
    tags: ['Auto Cast', 'Auto Reel', 'Perfect Timing', 'Hotspot Teleport'],
    badges: [{ text: 'POPULAR', type: 'hot' }],
    stats: { rating: '4.9', users: '1.7M', size: '3.2MB' },
    link: 'https://gamlob.online/cl/i/27legd',
  },
  {
    id: 'delta',
    title: 'Delta Executor App',
    description: 'Fast script execution with full mobile support and no key system',
    imageUrl: 'https://i.postimg.cc/XYfB1Lcm/41-Rt-Rhh9cg-L.jpg',
    iconUrl: 'https://i.postimg.cc/8C0G0wsG/41ZWmdpy-DRL-SL500.jpg',
    tags: ['Fast Execution', 'No Key', 'Mobile', 'Secure'],
    badges: [{ text: 'PRO', type: 'pro' }],
    stats: { rating: '4.8', users: '2.1M', size: '215MB' },
    link: 'https://gamlob.online/cl/i/w6ojnj',
  },
  {
    id: 'grow-garden',
    title: 'Grow a Garden Script',
    description: 'Full auto-farm, automatic planting and harvesting, infinite seeds and anti-afk',
    imageUrl: 'https://i.postimg.cc/cJqYpCwr/1761588125791.jpg',
    iconUrl: 'https://i.postimg.cc/zfB574zW/f5258d61-b719-4f42-b12b-f02f81fad283-png.png',
    tags: ['Auto Farm', 'Infinite Seeds', 'Auto Harvest', 'Anti AFK'],
    badges: [{ text: 'POPULAR', type: 'hot' }],
    stats: { rating: '4.8', users: '3.2M', size: '2.4MB' },
    link: 'https://gamlob.online/cl/i/l7kmgk',
  },
];
